# Generated by Django 3.2b1 on 2021-03-23 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VueCrudData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='名前')),
                ('comment', models.TextField(default='', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRUD',
                'db_table': 'vue_crud_data',
            },
        ),
        migrations.CreateModel(
            name='VueCrudDataBk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='名前')),
                ('comment', models.TextField(default='', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRUD(BK)',
                'db_table': 'vue_crud_data_bk',
            },
        ),
    ]
